name: Build Wasm Simd Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the image to build'
        required: true
        type: string

env:
   REGISTRY: ghcr.io
   ORG: cosmos
   IMAGE_NAME: ibc-go-wasm-simd
   GIT_TAG: "${{ inputs.tag }}"

jobs:
   build-image-at-tag:
      strategy:
        matrix: 
          build: 
            - os: ubuntu-latest
              platform: linux/amd64
            - os: macos-latest
              platform: linux/arm64
      runs-on: 
      steps:
         - uses: actions/checkout@v4
           with:
            ref: "${{ env.GIT_TAG }}"
            fetch-depth: 0
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Log in to the Container registry
           uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: Get docker tag
           run: echo "DOCKER_TAG=$(echo $GIT_TAG | sed 's/[^a-zA-Z0-9\.]/-/g')" >> $GITHUB_ENV
         - name: Build and push
           uses: docker/build-push-action@v6
           with:
             platforms: ${{ matrix.platform }}
             push: true
             tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
             file: modules/light-clients/08-wasm/Dockerfile

